CREATE OR REPLACE VIEW candidate_reviews_given_view AS
SELECT *
FROM candidate_poll p
WHERE
        p.Ok_overall = 1;

CREATE OR REPLACE VIEW candidate_reviews_received_view AS
SELECT *
FROM candidate_poll p
WHERE
    p.Ok_overall = 1
    AND
    p.Reviewee != p.Reviewer;
	/*the own review is not added here -- this is correct*/

CREATE OR REPLACE VIEW candidate_teammember_view AS
SELECT *
FROM candidate_poll p
WHERE
    p.Reviewee != p.Reviewer
    AND
    p.Reviewer NOT IN (
        SELECT Manager
        FROM department
    )
    AND
    p.Reviewer = ANY (
            SELECT User
            FROM user_department
            WHERE Department = (
                SELECT Department
                FROM user_department
                WHERE User = p.Reviewee
            )
            /* get reviewers being member of reviewee's department */
    )
    AND Ok_overall = 1;

CREATE OR REPLACE VIEW candidate_notteammember_view AS
SELECT *
FROM candidate_poll p
WHERE
    p.Reviewee != p.Reviewer
    AND
    p.Reviewer NOT IN (
        SELECT Manager
        FROM department
    /*here you exclude all managers please explain this being complementary to above statement */
    )
    AND
    p.Reviewer NOT IN (
        SELECT User
        FROM user_department
        WHERE Department = (
            SELECT Department
            FROM user_department
            WHERE User = p.Reviewee
        )
    /*exclude members of your department regardless them being manager */
    )
    AND Ok_overall = 1;

CREATE OR REPLACE VIEW candidate_teammanager_view AS
SELECT *
FROM candidate_poll p
WHERE
    p.Reviewee != p.Reviewer
    AND
    p.Reviewer = ANY (
    	SELECT Manager
        FROM department
        WHERE ID = (
            SELECT Department
            FROM user_department
            WHERE ID = p.Reviewee
        )
    )
    AND
    Ok_overall = 1;

CREATE OR REPLACE VIEW candidate_notteammanager_view AS
SELECT *
FROM candidate_poll p
WHERE
    p.Reviewee != p.Reviewer
    AND
    p.Reviewer = ANY (
    	SELECT Manager
        FROM department
        WHERE
        	ID != (
            	SELECT Department
           		FROM user_department
            	WHERE User = p.Reviewee
        	)
    )
    AND
    Ok_overall = 1;

CREATE OR REPLACE VIEW candidate_preferred_reviewers_view AS
SELECT DISTINCT(p.ID), p.Reviewer, p.Reviewee
FROM candidate_poll p
JOIN preferred_poll pf ON p.Reviewer = pf.Reviewer
WHERE   pf.user = p.Reviewee
        AND p.Ok_overall = 1;
/* explain why candidate_poll table is needed for this query */
/* First you check what users are preferred. 
 * Then you look in the candidate_poll table, to which 'preferred couples' are actually generated by the algorithm (these are stored in the candidate_poll table) */

CREATE OR REPLACE VIEW candidate_preferred_reviewees_view AS
SELECT DISTINCT(p.ID), p.Reviewer, p.Reviewee
FROM candidate_poll p
JOIN preferred_poll pf ON p.Reviewee = pf.Reviewee
WHERE   pf.user = p.Reviewer
        AND p.Ok_overall = 1;
/* explain why candidate_poll table is needed for this query */